SELECT * FROM JOGO;
--SELECT * FROM CLUBE;
SELECT * FROM CLASSIFICACAO;

--SELECT PARA ACHAR O CAMPEAO
SELECT TOP 1 C.NOME, C.APELIDO, CC.PONTUACAO, CC.SALDO_GOLS
FROM CLASSIFICACAO CC
JOIN CLUBE C ON CC.ID_CLUBE = C.ID
ORDER BY CC.PONTUACAO DESC, CC.SALDO_GOLS DESC;

--SELECT PARA FAZER O RANKING TOP 5
SELECT C.NOME, C.APELIDO, CC.PONTUACAO, CC.SALDO_GOLS
FROM CLASSIFICACAO CC
JOIN CLUBE C ON CC.ID_CLUBE = C.ID
ORDER BY CC.PONTUACAO DESC, CC.SALDO_GOLS DESC;

--SELECT PARA ACHAR O TIME QUE MAIS FEZ GOLS NO CAMPEONATO
SELECT TOP 1 C.NOME, C.APELIDO, CC.GOLS_FEITOS
FROM CLASSIFICACAO CC
JOIN CLUBE C ON CC.ID_CLUBE = C.ID
ORDER BY CC.GOLS_FEITOS DESC;

--SELECT PARA ACHAR O TIME QUE MAIS BAGRE
SELECT TOP 1 C.NOME, C.APELIDO, CC.GOLS_SOFRIDOS
FROM CLASSIFICACAO CC
JOIN CLUBE C ON CC.ID_CLUBE = C.ID
ORDER BY CC.GOLS_SOFRIDOS DESC;

--SELECT PARA ACHAR O JOGO QUE MAIS TEVE GOLS
SELECT TOP 1 JJ.ID_JOGO, JJ.GOLS_TOTAIS_JOGO
FROM JOGO JJ
ORDER BY JJ.GOLS_TOTAIS_JOGO DESC;

--SELECT PARA VER A MAIOR QUANTIDADE DE GOLS DE CADA TIME EM UM JOGO (SENDO MANDANTE E VISITANTE)
SELECT
    c.NOME AS NomeClube, MAX(j.GOLS_CASA) AS MaiorQtdGolsSendoMandante, MAX(j.GOLS_VISITA) AS MaiorQtdGolsSendoVisitante
FROM 
    CLUBE c JOIN JOGO j ON c.ID = j.ID_CASA OR c.ID = j.ID_VISITA
GROUP BY
    c.NOME;